import "~/styles/globals.css";

import { cookies } from "next/headers";
import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import { ClientGlobal } from "./_components/ClientGlobal";

const font = GeistSans;

export const metadata = {
  title: "Todo Playlist LASTFM",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon_vercel.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${font.className} dark font-sans antialiased`}>
      <body>
        <TRPCReactProvider cookies={cookies().toString()}>
          <main className="flex min-h-screen flex-col">{children}</main>
        </TRPCReactProvider>
        <ClientGlobal />
      </body>
    </html>
  );
}
