import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import { ClientGlobal } from "./_components/ClientGlobal";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Todo Playlist LASTFM",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon_vercel.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <main className="flex min-h-screen flex-col">{children}</main>
        </TRPCReactProvider>
        <ClientGlobal />
      </body>
    </html>
  );
}
